
BEGIN;

CREATE TABLE IF NOT EXISTS USERS (
	ID VARCHAR(255) PRIMARY KEY NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    PWD VARCHAR(255) NOT NULL,
    NICKNAME VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS POSTS (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      USERID VARCHAR(255) NOT NULL,
      TITLE VARCHAR(255) NOT NULL,
      NICKNAME VARCHAR(255),
      TEXTCONTENT TEXT,
      CATEGORY VARCHAR(255) NOT NULL,
      REFERENCEDID INT,
      CREATEDAT DATETIME,
      UPDATEDAT DATETIME,
      FOREIGN KEY (USERID) REFERENCES USERS(ID)
);


COMMIT;